### ISSUE TITLE
App module now shown on Kotlin Native

### ISSUE THREAD

**Issue by BulatMukhutdinov** [HMS-Core/hms-codelabs#4]
I have a project using kotlin multiplatform. When I start the configuration wizard Android App Module list is empty.

**Comment by Mike-mei** [comment]
It may caused by importing the whole project directly.
<img width="255" alt="20210304-150916(eSpace)" src="https://user-images.githubusercontent.com/63704034/109924409-31425b80-7cfb-11eb-9762-6092281f71f1.png">
There are seperated code for different kits in this repo, please just import the code you want and try again.
<img width="288" alt="20210304-150921(eSpace)" src="https://user-images.githubusercontent.com/63704034/109924448-3e5f4a80-7cfb-11eb-84c0-3c6e51050fca.png">

**Comment by BulatMukhutdinov** [comment]
Sorry, probably it is not the best place to ask this question, but I don't know where to report it.

I have a project which is using KMM https://kotlinlang.org/docs/mobile/getting-started.html

When I am trying to configure wizard the list of app modules is empty

![image](https://user-images.githubusercontent.com/1418811/109938008-98064b80-7ce0-11eb-97f0-473def9fb5f3.png)

**Comment by Mike-mei** [comment]
Firstly check whether the project is compiled successfully. If the project is compiled but still cannot be identified, please provide 2 build.gradle files. 
Please check if the Modules under Project Structure match that in this image.
![0F7E4CC9-08C1-46A1-9C87-360DC3C8EAF6](https://user-images.githubusercontent.com/63704034/110266842-a4004f00-7ff9-11eb-9da5-9b3812d373e3.png)
